#!/usr/bin/env python3
"""wrap.py — bundle a game's Luau sources into one requireable Luau module.

Why this exists. The luau CLI has no file IO and no `setfenv`, so `emu/harness.luau` cannot
read a game's source on its own, and it cannot inject a fake `game` / `Instance` into a module
loaded with `require`: the CLI sandboxes every required module behind its own globals table.

What it CAN do is `loadstring`, and a `loadstring` chunk shares the globals of the module that
compiled it. So the harness sets `game`, `Instance`, `task`, ... as its own globals and then
compiles each game script itself. This script's only job is to get the source text in there:
it emits a Luau module that returns

    { ["shared/Config"] = "<verbatim source>", ["server/Main.server"] = "...", ... }

as long-bracket strings, so nothing is escaped or reformatted and line numbers stay exact —
`loadstring(src, "@" .. realPath)` then reports errors at the real file and the real line.

Usage:
    py -3 wrap.py --game ../grow-a-crystal --out build/grow-a-crystal.luau
    py -3 wrap.py --game ../labyrint-spill --out build/labyrint-spill.luau

Reads only. Never writes inside a game's `src/` (SPEC.md rule 2).
"""

import argparse
import os
import sys

SUBDIRS = ("shared", "server", "client")


def pick_bracket_level(texts):
    """Smallest `=` run that cannot terminate a long bracket in any of these sources.

    A long string opened with [===[ ends at the first ]===]. Picking a level whose closer does
    not occur in the text keeps the source verbatim without a single escape.
    """
    for level in range(0, 32):
        closer = "]" + "=" * level + "]"
        opener = "[" + "=" * level + "["
        if all(closer not in t and opener not in t for t in texts):
            return level
    raise SystemExit("wrap.py: no usable long-bracket level; a source contains every one")


def collect(game_dir):
    """-> [(module key, absolute path, source text)] sorted for a stable bundle."""
    out = []
    for sub in SUBDIRS:
        d = os.path.join(game_dir, "src", sub)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".luau"):
                continue
            path = os.path.join(d, name)
            with open(path, "r", encoding="utf-8") as fh:
                text = fh.read()
            key = sub + "/" + name[: -len(".luau")]
            out.append((key, os.path.abspath(path), text))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--game", required=True, help="a game directory (the one holding src/)")
    ap.add_argument("--out", required=True, help="the .luau bundle to write")
    args = ap.parse_args(argv)

    game_dir = os.path.abspath(args.game)
    if not os.path.isdir(os.path.join(game_dir, "src")):
        raise SystemExit("wrap.py: no src/ under " + game_dir)

    entries = collect(game_dir)
    if not entries:
        raise SystemExit("wrap.py: found no .luau sources under " + game_dir)

    level = pick_bracket_level([t for _, _, t in entries])
    opener = "[" + "=" * level + "["
    closer = "]" + "=" * level + "]"

    lines = [
        "-- GENERATED by robloxemu/wrap.py. Do not edit; re-run the generator.",
        "-- Source game: " + os.path.basename(game_dir),
        "--",
        "-- Each value is one game script, verbatim. The harness compiles these with",
        "-- loadstring so they run against the fake `game`/`Instance` globals; keeping them",
        "-- as long strings means line numbers in a stack trace match the real file.",
        "return {",
    ]
    for key, path, text in entries:
        # A long string swallows one newline immediately after the opener, so open with an
        # explicit newline and line 1 of the source stays line 1 of the chunk.
        lines.append('\t["%s"] = { path = "%s", source = %s\n%s%s },'
                     % (key, path.replace("\\", "/"), opener, text, closer))
    lines.append("}")

    out_path = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    print("wrap.py: %d modules -> %s (bracket level %d)" % (len(entries), out_path, level))
    for key, _, text in entries:
        print("    %-34s %5d lines" % (key, text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
